import '../tailwind/main.scss';
import './variablesGlobales';
import './filtros';
import './agregar_al_carro';
import './paypal';
import './calendario';
import './header';
import './borrar_perfil';
import './eliminar_del_carro';